-- MySQL Script generated by MySQL Workbench
-- Sun Sep  1 07:52:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kategori` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kategori` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pengaduan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pengaduan` (
  `id` INT NOT NULL,
  `body` TEXT NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `Status` ENUM('SUDAH', 'BELUM') NULL,
  `tgl` DATE NULL,
  `kategori_id` INT NULL AUTO_INCREMENT,
  `kategori_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pengaduan_kategori1_idx` (`kategori_id1` ASC) VISIBLE,
  CONSTRAINT `fk_pengaduan_kategori1`
    FOREIGN KEY (`kategori_id1`)
    REFERENCES `mydb`.`kategori` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pengadu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pengadu` (
  `id` INT NOT NULL,
  `nik` INT(10) NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `no_wa` VARCHAR(45) NOT NULL,
  `tiket_id` INT NULL AUTO_INCREMENT,
  `pengaduan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pengadu_pengaduan_idx` (`pengaduan_id` ASC) VISIBLE,
  CONSTRAINT `fk_pengadu_pengaduan`
    FOREIGN KEY (`pengaduan_id`)
    REFERENCES `mydb`.`pengaduan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tanggapan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tanggapan` (
  `id` INT NOT NULL,
  `body` TEXT NOT NULL,
  `tanggapan` VARCHAR(45) NOT NULL,
  `pengaduan_id` INT NULL AUTO_INCREMENT,
  `pengaduan_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tanggapan_pengaduan1_idx` (`pengaduan_id1` ASC) VISIBLE,
  CONSTRAINT `fk_tanggapan_pengaduan1`
    FOREIGN KEY (`pengaduan_id1`)
    REFERENCES `mydb`.`pengaduan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
